import { Home, LayoutTemplate, Settings, Trash } from "lucide-react";
import { Theme } from "./types";

export const data = {
  user: {
    name: "Shadcn",
    email: "shed@example.com",
    avatar: "/avatars/shadcn.png",
  },
  navItems: [
    {
      title: "Home",
      url: "/dashboard",
      icon: Home,
    },
    {
      title: "Templates",
      url: "/templates",
      icon: LayoutTemplate,
    },
    {
      title: "Trash",
      url: "/trash",
      icon: Trash,
    },
    {
      title: "Settings",
      url: "/settings",
      icon: Settings,
    },
  ],
};

export const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
    },
  },
};

export const itemVariants = {
  hidden: { y: 20, opacity: 0 },
  visible: {
    y: 0,
    opacity: 1,
    transition: {
      type: "spring",
      stiffness: 100,
    },
  },
};

// export const themes: Theme[] = [
// {
//     name:"",
//     fontFamily: "",
//     fontColor: "",
//     backgroundColor: "",
//     slideBackgroundColor: "",
//     accentColor: "" ,
//     gradientBackground : "",
//     slideColor: "",
//     navbarColor: "",
//     type: 'dark',
// }
// ]

// Themes data 1
// export const themes: Theme[] = [
//     {
//       name: "Midnight Blue",
//       fontFamily: "Arial, sans-serif",
//       fontColor: "#FFFFFF",
//       backgroundColor: "#1B1F3B",
//       slideBackgroundColor: "#2A2D4A",
//       accentColor: "#4C5BCE",
//       gradientBackground: "linear-gradient(135deg, #1B1F3B, #4C5BCE)",
//       slideColor: "#2A2D4A",
//       navbarColor: "#23284D",
//       type: "dark",
//     },
//     {
//       name: "Sunset Glow",
//       fontFamily: "Poppins, sans-serif",
//       fontColor: "#2D2D2D",
//       backgroundColor: "#FFD166",
//       slideBackgroundColor: "#FFA45B",
//       accentColor: "#FF5733",
//       gradientBackground: "linear-gradient(135deg, #FFD166, #FF5733)",
//       slideColor: "#FFA45B",
//       navbarColor: "#E67E22",
//       type: "light",
//     },
//     {
//       name: "Emerald Dream",
//       fontFamily: "Roboto, sans-serif",
//       fontColor: "#FFFFFF",
//       backgroundColor: "#004D40",
//       slideBackgroundColor: "#00796B",
//       accentColor: "#26A69A",
//       gradientBackground: "linear-gradient(135deg, #004D40, #26A69A)",
//       slideColor: "#00796B",
//       navbarColor: "#004D40",
//       type: "dark",
//     },
//     {
//       name: "Cherry Blossom",
//       fontFamily: "Georgia, serif",
//       fontColor: "#3D3D3D",
//       backgroundColor: "#FFC1E3",
//       slideBackgroundColor: "#FF9EBB",
//       accentColor: "#FF6F91",
//       gradientBackground: "linear-gradient(135deg, #FFC1E3, #FF6F91)",
//       slideColor: "#FF9EBB",
//       navbarColor: "#FF6F91",
//       type: "light",
//     },
//     {
//       name: "Cyber Neon",
//       fontFamily: "Courier New, monospace",
//       fontColor: "#0FF0FC",
//       backgroundColor: "#050505",
//       slideBackgroundColor: "#101010",
//       accentColor: "#00F5D4",
//       gradientBackground: "linear-gradient(135deg, #050505, #00F5D4)",
//       slideColor: "#101010",
//       navbarColor: "#080808",
//       type: "dark",
//     },
//     {
//       name: "Forest Mist",
//       fontFamily: "Lora, serif",
//       fontColor: "#2E2E2E",
//       backgroundColor: "#D4E157",
//       slideBackgroundColor: "#A5D6A7",
//       accentColor: "#43A047",
//       gradientBackground: "linear-gradient(135deg, #D4E157, #43A047)",
//       slideColor: "#A5D6A7",
//       navbarColor: "#7CB342",
//       type: "light",
//     },
//     {
//       name: "Dark Mode Pro",
//       fontFamily: "Montserrat, sans-serif",
//       fontColor: "#F5F5F5",
//       backgroundColor: "#121212",
//       slideBackgroundColor: "#1E1E1E",
//       accentColor: "#BB86FC",
//       gradientBackground: "linear-gradient(135deg, #121212, #BB86FC)",
//       slideColor: "#1E1E1E",
//       navbarColor: "#1A1A1A",
//       type: "dark",
//     },
//     {
//       name: "Ocean Breeze",
//       fontFamily: "Open Sans, sans-serif",
//       fontColor: "#025E73",
//       backgroundColor: "#B2EBF2",
//       slideBackgroundColor: "#80DEEA",
//       accentColor: "#0288D1",
//       gradientBackground: "linear-gradient(135deg, #B2EBF2, #0288D1)",
//       slideColor: "#80DEEA",
//       navbarColor: "#0097A7",
//       type: "light",
//     },
//     {
//       name: "Royal Gold",
//       fontFamily: "Playfair Display, serif",
//       fontColor: "#D4AF37",
//       backgroundColor: "#1A1A1A",
//       slideBackgroundColor: "#333333",
//       accentColor: "#FFD700",
//       gradientBackground: "linear-gradient(135deg, #1A1A1A, #FFD700)",
//       slideColor: "#333333",
//       navbarColor: "#2C2C2C",
//       type: "dark",
//     },
//     {
//       name: "Lavender Fields",
//       fontFamily: "Nunito, sans-serif",
//       fontColor: "#5D4157",
//       backgroundColor: "#E6E6FA",
//       slideBackgroundColor: "#D8BFD8",
//       accentColor: "#8A2BE2",
//       gradientBackground: "linear-gradient(135deg, #E6E6FA, #8A2BE2)",
//       slideColor: "#D8BFD8",
//       navbarColor: "#9370DB",
//       type: "light",
//     },
//   ];

// Themes data 2
export const themes: Theme[] = [
  {
    name: "Celestial Night",
    fontFamily: "Merriweather, serif",
    fontColor: "#E0E0E0",
    backgroundColor: "#0D1B2A",
    slideBackgroundColor: "#1B263B",
    accentColor: "#415A77",
    gradientBackground: "linear-gradient(135deg, #0D1B2A, #415A77)",
    slideColor: "#1B263B",
    navbarColor: "#0F1626",
    type: "dark",
  },
  {
    name: "Autumn Harvest",
    fontFamily: "Lora, serif",
    fontColor: "#5A3222",
    backgroundColor: "#FFEDD5",
    slideBackgroundColor: "#F4A261",
    accentColor: "#E76F51",
    gradientBackground: "linear-gradient(135deg, #FFEDD5, #E76F51)",
    slideColor: "#F4A261",
    navbarColor: "#E07A5F",
    type: "light",
  },
  // {
  //   name: "Electric Purple",
  //   fontFamily: "Oswald, sans-serif",
  //   fontColor: "#F8F8F8",
  //   backgroundColor: "#3B0086",
  //   slideBackgroundColor: "#5D00B6",
  //   accentColor: "#9900FF",
  //   gradientBackground: "linear-gradient(135deg, #3B0086, #9900FF)",
  //   slideColor: "#5D00B6",
  //   navbarColor: "#28004D",
  //   type: "dark",
  // },
  {
    name: "Serene Pastel",
    fontFamily: "Quicksand, sans-serif",
    fontColor: "#3A3A3A",
    backgroundColor: "#FFFAF0",
    slideBackgroundColor: "#FFE4E1",
    accentColor: "#FFB6C1",
    gradientBackground: "linear-gradient(135deg, #FFFAF0, #FFB6C1)",
    slideColor: "#FFE4E1",
    navbarColor: "#FFC0CB",
    type: "light",
  },
  {
    name: "Stormy Sky",
    fontFamily: "Raleway, sans-serif",
    fontColor: "#D3D3D3",
    backgroundColor: "#1E1E24",
    slideBackgroundColor: "#2C2C34",
    accentColor: "#4A4E69",
    gradientBackground: "linear-gradient(135deg, #1E1E24, #4A4E69)",
    slideColor: "#2C2C34",
    navbarColor: "#3C3F58",
    type: "dark",
  },
  {
    name: "Golden Sand",
    fontFamily: "Playfair Display, serif",
    fontColor: "#5B3E31",
    backgroundColor: "#F5DEB3",
    slideBackgroundColor: "#E3B778",
    accentColor: "#D89B5E",
    gradientBackground: "linear-gradient(135deg, #F5DEB3, #D89B5E)",
    slideColor: "#E3B778",
    navbarColor: "#C68E55",
    type: "light",
  },
  // {
  //   name: "Crimson Velvet",
  //   fontFamily: "Poppins, sans-serif",
  //   fontColor: "#F5F5F5",
  //   backgroundColor: "#7D0A0A",
  //   slideBackgroundColor: "#9A1818",
  //   accentColor: "#D72638",
  //   gradientBackground: "linear-gradient(135deg, #7D0A0A, #D72638)",
  //   slideColor: "#9A1818",
  //   navbarColor: "#5A0808",
  //   type: "dark",
  // },
  {
    name: "Arctic Ice",
    fontFamily: "Roboto, sans-serif",
    fontColor: "#00334E",
    backgroundColor: "#E0F7FA",
    slideBackgroundColor: "#B3E5FC",
    accentColor: "#03A9F4",
    gradientBackground: "linear-gradient(135deg, #E0F7FA, #03A9F4)",
    slideColor: "#B3E5FC",
    navbarColor: "#0288D1",
    type: "light",
  },
  {
    name: "Neon Matrix",
    fontFamily: "Source Code Pro, monospace",
    fontColor: "#00FF41",
    backgroundColor: "#000000",
    slideBackgroundColor: "#1A1A1A",
    accentColor: "#33FF66",
    gradientBackground: "linear-gradient(135deg, #000000, #33FF66)",
    slideColor: "#1A1A1A",
    navbarColor: "#0D0D0D",
    type: "dark",
  },
  {
    name: "Sakura Petal",
    fontFamily: "Cormorant Garamond, serif",
    fontColor: "#8B5A2B",
    backgroundColor: "#FCE4EC",
    slideBackgroundColor: "#F8BBD0",
    accentColor: "#EC407A",
    gradientBackground: "linear-gradient(135deg, #FCE4EC, #EC407A)",
    slideColor: "#F8BBD0",
    navbarColor: "#D81B60",
    type: "light",
  },
  {
    name: "Futuristic Cyan",
    fontFamily: "Exo, sans-serif",
    fontColor: "#FFFFFF",
    backgroundColor: "#012E40",
    slideBackgroundColor: "#025E73",
    accentColor: "#00CED1",
    gradientBackground: "linear-gradient(135deg, #012E40, #00CED1)",
    slideColor: "#025E73",
    navbarColor: "#013A4A",
    type: "dark",
  },
  {
    name: "Desert Mirage",
    fontFamily: "Lato, sans-serif",
    fontColor: "#784F32",
    backgroundColor: "#F5E1A4",
    slideBackgroundColor: "#E4C580",
    accentColor: "#D4A373",
    gradientBackground: "linear-gradient(135deg, #F5E1A4, #D4A373)",
    slideColor: "#E4C580",
    navbarColor: "#C19A6B",
    type: "light",
  },
  {
    name: "Midnight Teal",
    fontFamily: "Bebas Neue, sans-serif",
    fontColor: "#E8E8E8",
    backgroundColor: "#002F2F",
    slideBackgroundColor: "#004D4D",
    accentColor: "#26C6DA",
    gradientBackground: "linear-gradient(135deg, #002F2F, #26C6DA)",
    slideColor: "#004D4D",
    navbarColor: "#003838",
    type: "dark",
  },
  {
    name: "Citrus Punch",
    fontFamily: "Ubuntu, sans-serif",
    fontColor: "#5A3E21",
    backgroundColor: "#FFF176",
    slideBackgroundColor: "#FFCC80",
    accentColor: "#FF9800",
    gradientBackground: "linear-gradient(135deg, #FFF176, #FF9800)",
    slideColor: "#FFCC80",
    navbarColor: "#F57C00",
    type: "light",
  },
  {
    name: "Obsidian Shadow",
    fontFamily: "Inter, sans-serif",
    fontColor: "#FFFFFF",
    backgroundColor: "#111111",
    slideBackgroundColor: "#222222",
    accentColor: "#757575",
    gradientBackground: "linear-gradient(135deg, #111111, #757575)",
    slideColor: "#222222",
    navbarColor: "#1A1A1A",
    type: "dark",
  },
  {
    name: "Velvet Rose",
    fontFamily: "Dancing Script, cursive",
    fontColor: "#5D1E1E",
    backgroundColor: "#FFDFDF",
    slideBackgroundColor: "#FFB3B3",
    accentColor: "#E57373",
    gradientBackground: "linear-gradient(135deg, #FFDFDF, #E57373)",
    slideColor: "#FFB3B3",
    navbarColor: "#D32F2F",
    type: "light",
  },
  {
    name: "Peach Bloom",
    fontFamily: "Merriweather, serif",
    fontColor: "#5A3E36",
    backgroundColor: "#FFE5D9",
    slideBackgroundColor: "#FFCAB1",
    accentColor: "#FF8A65",
    gradientBackground: "linear-gradient(135deg, #FFE5D9, #FF8A65)",
    slideColor: "#FFCAB1",
    navbarColor: "#E57373",
    type: "light",
  },
  {
    name: "Misty Lavender",
    fontFamily: "Lora, serif",
    fontColor: "#4A3753",
    backgroundColor: "#E6E6FA",
    slideBackgroundColor: "#D8BFD8",
    accentColor: "#A370B5",
    gradientBackground: "linear-gradient(135deg, #E6E6FA, #A370B5)",
    slideColor: "#D8BFD8",
    navbarColor: "#9370DB",
    type: "light",
  },
  {
    name: "Muted Ocean",
    fontFamily: "Poppins, sans-serif",
    fontColor: "#2C4A52",
    backgroundColor: "#BFD8D2",
    slideBackgroundColor: "#9DB4C0",
    accentColor: "#6B9080",
    gradientBackground: "linear-gradient(135deg, #BFD8D2, #6B9080)",
    slideColor: "#9DB4C0",
    navbarColor: "#52796F",
    type: "light",
  },
  {
    name: "Vintage Rose",
    fontFamily: "Playfair Display, serif",
    fontColor: "#5A2E2E",
    backgroundColor: "#F4D3D3",
    slideBackgroundColor: "#E8A9A9",
    accentColor: "#C08497",
    gradientBackground: "linear-gradient(135deg, #F4D3D3, #C08497)",
    slideColor: "#E8A9A9",
    navbarColor: "#A56A6A",
    type: "light",
  },
  {
    name: "Deep Plum",
    fontFamily: "Raleway, sans-serif",
    fontColor: "#E0E0E0",
    backgroundColor: "#3A0B42",
    slideBackgroundColor: "#55286F",
    accentColor: "#764BA2",
    gradientBackground: "linear-gradient(135deg, #3A0B42, #764BA2)",
    slideColor: "#55286F",
    navbarColor: "#2C0D44",
    type: "dark",
  },
  {
    name: "Obsidian Night",
    fontFamily: "Montserrat, sans-serif",
    fontColor: "#E0E0E0",
    backgroundColor: "#121212",
    slideBackgroundColor: "#1A1A1A",
    accentColor: "#FF4500",
    gradientBackground: "linear-gradient(135deg, #121212, #FF4500)",
    slideColor: "#1A1A1A",
    navbarColor: "#191919",
    type: "dark",
  },
  {
    name: "Shadow Emerald",
    fontFamily: "Poppins, sans-serif",
    fontColor: "#C8E6C9",
    backgroundColor: "#102820",
    slideBackgroundColor: "#1B3A30",
    accentColor: "#4CAF50",
    gradientBackground: "linear-gradient(135deg, #102820, #4CAF50)",
    slideColor: "#1B3A30",
    navbarColor: "#0F261D",
    type: "dark",
  },
  {
    name: "Cosmic Purple",
    fontFamily: "Raleway, sans-serif",
    fontColor: "#E0C3FC",
    backgroundColor: "#2A0845",
    slideBackgroundColor: "#3B0973",
    accentColor: "#BB86FC",
    gradientBackground: "linear-gradient(135deg, #2A0845, #BB86FC)",
    slideColor: "#3B0973",
    navbarColor: "#25073A",
    type: "dark",
  },
  {
    name: "Steel Noir",
    fontFamily: "Roboto, sans-serif",
    fontColor: "#D1D1D1",
    backgroundColor: "#1C1C1C",
    slideBackgroundColor: "#2B2B2B",
    accentColor: "#FF6F61",
    gradientBackground: "linear-gradient(135deg, #1C1C1C, #FF6F61)",
    slideColor: "#2B2B2B",
    navbarColor: "#232323",
    type: "dark",
  },
  {
    name: "Nebula Blue",
    fontFamily: "Lato, sans-serif",
    fontColor: "#A7C7E7",
    backgroundColor: "#040D21",
    slideBackgroundColor: "#102A43",
    accentColor: "#1E90FF",
    gradientBackground: "linear-gradient(135deg, #040D21, #1E90FF)",
    slideColor: "#102A43",
    navbarColor: "#081A31",
    type: "dark",
  },
  {
    name: "Minimal Mono",
    fontFamily: "Inter, sans-serif",
    fontColor: "#222222", // Dark gray for readability
    backgroundColor: "#F5F5F5", // Soft white for a clean look
    slideBackgroundColor: "#EAEAEA", // Slightly darker gray for subtle contrast
    accentColor: "#000000", // Pure black for sharp highlights
    gradientBackground: "linear-gradient(135deg, #F5F5F5, #EAEAEA)", // Soft gradient for smoothness
    slideColor: "#EAEAEA",
    navbarColor: "#DCDCDC", // Light gray for a cohesive appearance
    type: "light",
  },
];

export const CreatePageCard = [
  {
    title: "Use a",
    highlightedText: "Template",
    description: "Write a prompt and leave everything else for us to handle",
    type: "template",
  },
  {
    title: "Generate with",
    highlightedText: "Creative AI",
    description: "Write a prompt and leave everything else for us to handle",
    type: "creative-ai",
    highlight: true,
  },
  {
    title: "Start from",
    highlightedText: "Scratch",
    description: "Write a prompt and leave everything else for us to handle",
    type: "create-scratch",
  },
];
