import { CircleOff } from "lucide-react";
import React from "react";

const NotFound = () => {
  return (
    <div className="flex flex-col min-h-[70vh] w-full justify-center items-center gap-12">
      {/* Circle Off Icon */}
      <CircleOff size={120}/>

      {/* Text */}
      <div className="flex flex-col items-center justify-center text-center">
        <p className="text-3xl font-semibold text-primary">Nothing to see here</p>

        {/* Random Image Generated by Creative AI */}
        <p className="text-base font-normal dark:text-secondary">
          So here is a random image generated by
          <span className="text-presai"> Creative AI</span>
        </p>
      </div>
    </div>
  );
};

export default NotFound;
